---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
 filter(product_name == "Okra") %>% 
  mutate(
    text_label = str_c("Added to cart order: ", add_to_cart_order, "\nReordered:", reordered)
  ) %>% 
  plot_ly(x = ~days_since_prior_order, type = "bar", text = ~text_label) %>% 
  layout(title = "Days Since Ordering Okra",
         xaxis = list(title = "Number of Days Since Prior Okra Order"),
         yaxis = list(title = "Count"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  filter(department == "snacks",
         aisle == "chips pretzels",
         str_detect(product_name, "Barbeque")) %>% 
  mutate(product_name = forcats::fct_reorder(product_name, order_hour_of_day)) %>% 
  plot_ly(x = ~product_name, y = ~order_hour_of_day, type = "box",
          color = ~product_name, colors = "viridis") %>% 
  layout(title = "Hour of the Day Barbeque Chips Are Ordered",
         xaxis = list(title = "Product Name"),
         yaxis = list(title = "Hour of Day"))
```

### Chart C

```{r}
instacart %>% 
  filter(department == "snacks",
         aisle == "chips pretzels",
         str_detect(product_name, "Barbeque")) %>% 
  mutate(product_name = forcats::fct_reorder(product_name, order_hour_of_day)) %>% 
  plot_ly(x = ~product_name, y = ~order_dow, type = "histogram",
          color = ~product_name, colors = "viridis") %>% 
  layout(title = "Day of the week Barbeque Chips Are Ordered",
         xaxis = list(title = "Product Name"),
         yaxis = list(title = "Day of the week")) 
```

